data:
  root: data/UTKFace
  splits: splits/fewshot_splits.json
model:
  arch: resnet18
  feat_dim: 512
train:
  batch_size: 64
  epochs: 30
  lr: 0.0005
  pretrained_ckpt: checkpoints/simclr_final.pt
